# Generated by Django 4.2 on 2024-01-26 12:57

from django.db import migrations, models
import django.db.models.deletion
import licensing.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("licensing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "license",
                    licensing.fields.License(
                        help_text="the license under which this content is published",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="licensing.license",
                        verbose_name="license",
                    ),
                ),
            ],
        ),
    ]
