# Generated by Django 4.2.5 on 2025-08-26 14:09

from django.db import migrations
import django.db.models.deletion
import licensing.fields


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_alter_license_options_remove_license_url_and_more'),
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='license',
            field=licensing.fields.LicenseField(help_text='The license under which this content is published', on_delete=django.db.models.deletion.PROTECT, to='licensing.license', verbose_name='license'),
        ),
    ]
