# Generated by Django 5.0.7 on 2025-08-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0002_alter_testmodel_license"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testmodel",
            old_name="license",
            new_name="content_license",
        ),
    ]
