# Generated by Django 4.1.5 on 2023-01-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The full name of the license as specified by https://spdx.org/licenses/",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A human-readable description of the license.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="Customary short name if applicable (e.g, GPLv3)",
                        max_length=255,
                        null=True,
                        verbose_name="short name",
                    ),
                ),
                (
                    "recommended",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the license is recommended for items in this dataset. Recommended items will show first in select boxes",
                        verbose_name="recommended",
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=True,
                        help_text="Licenses marked as hidden are allowed in the database but cannot be selected for new projects.",
                        verbose_name="hidden",
                    ),
                ),
                (
                    "spdx",
                    models.CharField(
                        blank=True,
                        help_text="Short identifier specified by https://spdx.org/licenses/",
                        max_length=16,
                        null=True,
                        unique=True,
                        verbose_name="SPDX ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="The main text of the license.",
                        verbose_name="text",
                    ),
                ),
                (
                    "html",
                    models.TextField(
                        blank=True,
                        help_text="The main text of the license as html.",
                        verbose_name="html",
                    ),
                ),
                (
                    "template",
                    models.TextField(
                        blank=True,
                        help_text="The main text of the license as a template.",
                        null=True,
                        verbose_name="template",
                    ),
                ),
                (
                    "urls",
                    models.JSONField(
                        default=list,
                        help_text="A list of URLs that link to an online resource describing the license.",
                        verbose_name="URLs",
                    ),
                ),
            ],
            options={
                "verbose_name": "license",
                "verbose_name_plural": "license",
                "db_table": "license_license",
            },
        ),
    ]
