name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, edited]
  workflow_dispatch:

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Load cached pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit checks
        run: poetry run pre-commit run --all-files

      - name: Check Poetry lock file consistency
        run: poetry lock --check

      - name: Static type checking with mypy
        run: poetry run mypy licensing/ || true  # Allow failure for now

      - name: Check for obsolete dependencies
        run: poetry run deptry . || true  # Allow failure for now

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Run bandit security linter
        run: |
          poetry add --group dev bandit[toml]
          poetry run bandit -r licensing/ -f json -o bandit-report.json || true

      - name: Upload bandit report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: bandit-report
          path: bandit-report.json

      - name: Run safety check for known vulnerabilities
        run: |
          poetry add --group dev safety
          poetry run safety check --json --output safety-report.json || true

      - name: Upload safety report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: safety-report
          path: safety-report.json

  package:
    name: Build Package
    runs-on: ubuntu-latest
    needs: [code-quality]
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Build package
        run: poetry build

      - name: Check package metadata
        run: poetry check

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
